/**
 * TypeScript Declaration Generator
 *
 * Generates a `.d.ts` file for the Riseup Macro SDK namespace,
 * providing IntelliSense for developers writing project scripts.
 *
 * See: spec/22-app-issues/75-sdk-namespace-enrichment-and-developer-tooling.md (R4)
 */

// eslint-disable-next-line max-lines-per-function
export function generateDts(): string {
  return `/**
 * Riseup Macro SDK — TypeScript Declarations
 *
 * Drop this file into your script project for IntelliSense support.
 * Generated by the Riseup Macro Extension.
 */

declare global {
  interface Window {
    RiseupAsiaMacroExt: RiseupAsiaMacroExtRoot;
    marco: MarcoSDK;
  }
}

/* ------------------------------------------------------------------ */
/*  Root                                                               */
/* ------------------------------------------------------------------ */

interface RiseupAsiaMacroExtRoot {
  Projects: Record<string, ProjectNamespace>;
  Settings: SettingsNamespace;
  docs: { llmGuide: string };
}

/* ------------------------------------------------------------------ */
/*  Settings Namespace                                                 */
/* ------------------------------------------------------------------ */

interface SettingsNamespace {
  readonly Broadcast: {
    /** HTTP proxy port (default 19280). */
    readonly Port: number;
    /** Full base URL for REST API (e.g. "http://localhost:19280"). */
    readonly BaseUrl: string;
  };
  readonly Logging: {
    /** Whether debug mode is enabled. */
    readonly DebugMode: boolean;
    /** Days to retain logs before auto-purge (0 = keep forever). */
    readonly RetentionDays: number;
  };
  readonly Injection: {
    /** Default script run-at timing. */
    readonly DefaultRunAt: "document_start" | "document_idle" | "document_end";
    /** Force legacy Blob URL injection (bypass chrome.userScripts). */
    readonly ForceLegacy: boolean;
    /** Default chat box XPath selector. */
    readonly ChatBoxXPath: string;
  };
  readonly Limits: {
    /** Maximum cycle count for macro loops. */
    readonly MaxCycleCount: number;
    /** Idle timeout in milliseconds. */
    readonly IdleTimeout: number;
  };
  readonly General: {
    /** Auto-run scripts on page load. */
    readonly AutoRunOnPageLoad: boolean;
    /** Show toast notifications. */
    readonly ShowNotifications: boolean;
    /** UI theme. */
    readonly Theme: "system" | "light" | "dark";
  };
}

/* ------------------------------------------------------------------ */
/*  Per-Project Namespace                                              */
/* ------------------------------------------------------------------ */

interface ProjectNamespace {
  vars: VarsModule;
  urls: UrlsModule;
  xpath: XPathModule;
  cookies: CookiesModule;
  kv: KvModule;
  files: FilesModule;
  meta: MetaModule;
  log: LogModule;
  db: DbModule;
  api: ApiModule;
  scripts: ReadonlyArray<ScriptInfo>;
  notify: NotifyModule;
  docs: DocsModule;
}

/* ------------------------------------------------------------------ */
/*  Sub-Modules                                                        */
/* ------------------------------------------------------------------ */

interface VarsModule {
  /** Read a project variable by key. */
  get(key: string): Promise<unknown>;
  /** Set a project variable. */
  set(key: string, value: unknown): Promise<void>;
  /** Get all project variables as a record. */
  getAll(): Promise<Record<string, unknown>>;
}

interface UrlsModule {
  /** Get the matched URL rule for the current page, or null. */
  getMatched(): UrlMatchResult | null;
  /** List all open tabs matching project URL rules. */
  listOpen(): TabInfo[];
  /** Get URL-template variables from labeled rules. */
  getVariables(): Record<string, string>;
}

interface UrlMatchResult {
  pattern: string;
  label?: string;
  matchType: "exact" | "prefix" | "regex" | "glob";
}

interface TabInfo {
  tabId: number;
  url: string;
  title?: string;
}

interface XPathModule {
  /** Get the chat box element using the configured XPath selector. */
  getChatBox(): Element | null;
}

interface CookieBindingInfo {
  /** The literal cookie name (e.g. "lovable-session-id.id"). */
  readonly cookieName: string;
  /** The URL scope for this cookie. */
  readonly url: string;
  /** Role: "session", "refresh", or "custom". */
  readonly role: string;
}

interface CookiesModule {
  /** Frozen array of cookie bindings declared for this project. */
  readonly bindings: readonly CookieBindingInfo[];
  /** Read a cookie by role name (e.g. "session") or literal cookie name. Role-based lookup is tried first. */
  get(nameOrRole: string): Promise<string | null>;
  /** Read a cookie value by its role (e.g. "session", "refresh"). */
  getByRole(role: string): Promise<string | null>;
  /** Convenience: reads the first "session" role cookie value. */
  getSessionToken(): Promise<string | null>;
  /** Get all cookies for the page URL. */
  getAll(): Promise<Record<string, string>>;
}

interface KvModule {
  /** Get a value by key from the project-scoped KV store. */
  get(key: string): Promise<unknown>;
  /** Set a key-value pair in the project-scoped KV store. */
  set(key: string, value: unknown): Promise<void>;
  /** Delete a key from the KV store. */
  delete(key: string): Promise<void>;
  /** List all keys in the KV store. */
  list(): Promise<string[]>;
}

interface FilesModule {
  /** Save a file to project-scoped storage. */
  save(name: string, data: string): Promise<void>;
  /** Read a file from project-scoped storage (async). */
  read(name: string): Promise<string>;
  /** List all files in project-scoped storage. */
  list(): Promise<string[]>;
  /** Pre-loaded file contents for synchronous access. Keys are filenames, values are file contents. */
  readonly cache: Readonly<Record<string, string>>;
}

interface MetaModule {
  /** Project display name. */
  readonly name: string;
  /** Semantic version string. */
  readonly version: string;
  /** URL-safe hyphen-case identifier. */
  readonly slug: string;
  /** PascalCase identifier used as SDK namespace key. */
  readonly codeName: string;
  /** Unique project UUID. */
  readonly id: string;
  /** Optional project description. */
  readonly description: string;
  /** Declared dependencies. */
  readonly dependencies: ReadonlyArray<{ projectId: string; version: string }>;
}

interface LogModule {
  /** Log an info-level message (persisted to SQLite). */
  info(message: string, meta?: Record<string, unknown>): void;
  /** Log a warning-level message. */
  warn(message: string, meta?: Record<string, unknown>): void;
  /** Log an error-level message. */
  error(message: string, meta?: Record<string, unknown>): void;
}

interface ScriptInfo {
  /** Script file name. */
  readonly name: string;
  /** Injection order (lower = earlier). */
  readonly order: number;
  /** Whether the script is enabled. */
  readonly isEnabled: boolean;
}

interface DbModule {
  /** Get a query builder for a specific table. */
  table(tableName: string): DbTableProxy;
}

interface DbTableProxy {
  /** Find multiple rows matching an optional where clause. */
  findMany(where?: Record<string, unknown>): Promise<Record<string, unknown>[]>;
  /** Create a new row. */
  create(data: Record<string, unknown>): Promise<Record<string, unknown>>;
  /** Update rows matching the where clause. */
  update(where: Record<string, unknown>, data: Record<string, unknown>): Promise<Record<string, unknown>>;
  /** Delete rows matching the where clause. */
  delete(where: Record<string, unknown>): Promise<void>;
  /** Count rows matching an optional where clause. */
  count(where?: Record<string, unknown>): Promise<number>;
}

interface ApiModule {
  kv: ApiKvModule;
  files: ApiFilesModule;
  db: ApiDbModule;
  schema: ApiSchemaModule;
}

interface ApiKvModule {
  get(key: string): Promise<unknown>;
  set(key: string, value: unknown): Promise<unknown>;
  delete(key: string): Promise<unknown>;
  list(): Promise<unknown>;
}

interface ApiFilesModule {
  save(name: string, data: string): Promise<unknown>;
  read(name: string): Promise<unknown>;
  list(): Promise<unknown>;
}

interface ApiDbModule {
  query(table: string, method: string, params?: Record<string, unknown>): Promise<unknown>;
}

interface ApiSchemaModule {
  list(): Promise<unknown>;
  create(table: string, columns: Array<{ name: string; type: string }>): Promise<unknown>;
  drop(table: string): Promise<unknown>;
}

interface NotifyModule {
  /** Show a toast notification. Returns a unique toast ID. */
  toast(message: string, level?: 'info' | 'warn' | 'error' | 'success', opts?: { duration?: number; copyable?: boolean }): string;
  /** Dismiss a specific toast by ID. */
  dismiss(id: string): void;
  /** Dismiss all visible toasts. */
  dismissAll(): void;
  /** Register a callback for error-level notifications. */
  onError(callback: (error: { message: string; timestamp: number; stack?: string }) => void): void;
  /** Get recent error entries. */
  getRecentErrors(): Array<{ message: string; timestamp: number; stack?: string }>;
}

interface DocsModule {
  readonly overview: string;
  readonly vars: string;
  readonly urls: string;
  readonly xpath: string;
  readonly cookies: string;
  readonly kv: string;
  readonly files: string;
  readonly meta: string;
  readonly log: string;
  readonly db: string;
  readonly api: string;
  readonly scripts: string;
  readonly notify: string;
}

/* ------------------------------------------------------------------ */
/*  Marco SDK (window.marco)                                           */
/* ------------------------------------------------------------------ */

interface MarcoSDK {
  readonly version: string;
  auth: MarcoAuth;
  cookies: MarcoCookies;
  config: MarcoConfig;
  xpath: MarcoXPath;
  kv: KvModule;
  files: FilesModule;
  log: LogModule;
  /** Show a toast notification in the page. */
  notify(message: string, level?: "info" | "success" | "warning" | "error", durationMs?: number): void;
  bridge?: MarcoBridge;
}

interface MarcoAuth {
  getToken(): Promise<string>;
  getSource(): string;
  refresh(): Promise<string>;
  isExpired(): boolean;
  getJwtPayload(): Record<string, unknown> | null;
}

interface MarcoCookies {
  get(name: string): Promise<string | null>;
  getDetail(name: string): Promise<{ value: string; domain: string } | null>;
  getAll(): Promise<Record<string, string>>;
}

interface MarcoConfig {
  get(key: string): Promise<unknown>;
  getAll(): Promise<Record<string, unknown>>;
  set(key: string, value: unknown): Promise<void>;
}

interface MarcoXPath {
  getChatBox(): Element | null;
  resolve(key: string): Element | null;
}

interface MarcoBridge {
  send(message: Record<string, unknown>): Promise<unknown>;
}

export {};
`;
}
