/**
 * MacroLoop Controller — JSON Schema Documentation
 *
 * Downloads the marco-db-schema reference as a Markdown file.
 *
 * @see spec/04-macro-controller/ts-migration-v2/05-module-splitting.md
 */

import { log } from '../logger';
import { SAMPLE_SCHEMA } from './database-json-types';

/** Trigger a browser download of the schema reference markdown. */
 
export function downloadSchemaDocs(): void {
  const md = `# Marco DB JSON Schema Reference

## Format: \`marco-db-schema/v1\`

### Top-level

| Field        | Type     | Description                          |
|-------------|----------|--------------------------------------|
| \`$schema\`   | string   | Schema version identifier            |
| \`tables\`    | array    | Table definitions to create          |
| \`migrations\`| array    | Migration operations to apply        |

### Table Definition

| Field          | Type     | Required | Description                         |
|---------------|----------|----------|-------------------------------------|
| \`name\`        | string   | ✓        | PascalCase table name               |
| \`ifNotExists\` | boolean  |          | Use CREATE TABLE IF NOT EXISTS      |
| \`columns\`     | array    | ✓        | Column definitions                  |
| \`foreignKeys\` | array    |          | Foreign key constraints             |

### Column Definition

| Field        | Type     | Required | Description                        |
|-------------|----------|----------|------------------------------------|
| \`name\`       | string   | ✓        | PascalCase column name             |
| \`type\`       | string   | ✓        | TEXT, INTEGER, REAL, BLOB, BOOLEAN |
| \`nullable\`   | boolean  |          | Allow NULL (default: true)         |
| \`unique\`     | boolean  |          | Add UNIQUE constraint              |
| \`default\`    | string   |          | SQL DEFAULT expression             |
| \`validation\` | object   |          | Validation rules (see below)       |

### Validation Rules

**String**: \`startsWith\`, \`endsWith\`, \`contains\`, \`minLength\`, \`maxLength\`
**Date**: \`format\` (ISO8601, YYYY-MM-DD)
**Regex**: \`pattern\`, \`flags\`

### Foreign Key

| Field        | Type     | Description                           |
|-------------|----------|---------------------------------------|
| \`column\`     | string   | Local column name                     |
| \`references\` | object   | \`{ table, column }\` of target        |
| \`onDelete\`   | string   | CASCADE, SET NULL, or RESTRICT        |
| \`onUpdate\`   | string   | CASCADE, SET NULL, or RESTRICT        |

### Migration Actions

| Action          | Fields needed                    |
|----------------|----------------------------------|
| \`addColumn\`    | \`table\`, \`column\` (definition)    |
| \`dropColumn\`   | \`table\`, \`column.name\` or \`oldName\` |
| \`renameColumn\` | \`table\`, \`oldName\`, \`newName\`     |

### Example

\`\`\`json
${JSON.stringify(SAMPLE_SCHEMA, null, 2)}
\`\`\`

---
*Generated by Marco DB Schema Tool — v1.73.0*
`;

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'marco-db-schema-reference.md';
  a.click();
  URL.revokeObjectURL(url);
  log('Downloaded schema documentation', 'info');
}
