#!/usr/bin/env node
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const AUDIT_SCAN_SCRIPT = resolve(SCRIPT_DIR, 'audit-scan.py');
const DEFAULT_SPEC_ROOT = 'spec/2026-spec';
const DEFAULT_REPORT_DIR = 'spec/2026-spec/_audit-2026-06-05';
const ROOT_ARG = '--root=';
const OUT_ARG = '--out=';
const PASS_BAR = 90;
const RED_BAR = 60;
const SCORE_FILE_FLOOR = 100;
const SCORE_COMPOSITE_FLOOR = 99.5;
const ROOT_FOLDER = '.';
const SNAPSHOT_FILE = 'scores.snapshot.json';

const SPEC_ROOT = resolve(getArg(ROOT_ARG, DEFAULT_SPEC_ROOT));
const REPORT_DIR = resolve(getArg(OUT_ARG, DEFAULT_REPORT_DIR));

const rows = readAuditRows(SPEC_ROOT);
const groups = groupRows(rows);
const reports = createReports(rows, groups);
writeReports(REPORT_DIR, reports);
console.log(`[render-reports] OK — wrote ${reports.length} report(s) to ${REPORT_DIR}`);

function getArg(prefix, fallback) {
  return process.argv.find((value) => value.startsWith(prefix))?.slice(prefix.length) ?? fallback;
}

function readAuditRows(specRoot) {
  const result = spawnSync('python3', [AUDIT_SCAN_SCRIPT, specRoot], { encoding: 'utf8' });
  if (result.status === 0) {
    return JSON.parse(result.stdout);
  }

  throw new Error(`audit-scan.py failed for exact path ${specRoot}; missing item: score JSON; reason: ${result.stderr}`);
}

function groupRows(items) {
  const groups = new Map();
  for (const row of items) {
    const folder = getFolderName(row.path);
    const currentRows = groups.get(folder) ?? [];
    groups.set(folder, [...currentRows, row]);
  }

  return groups;
}

function getFolderName(path) {
  return path.includes('/') ? path.split('/')[0] : ROOT_FOLDER;
}

function createReports(items, groupedRows) {
  const folderReports = getSourceFolderNames(groupedRows).map((folder, index) => {
    return [getFolderReportName(index, folder), renderFolder(groupedRows.get(folder) ?? [], folder)];
  });

  return [
    ['README.md', renderIndex(items, groupedRows)],
    ['00-method.md', renderMethod(items, groupedRows)],
    ['01-aggregate-scoreboard.md', renderScoreboard(items)],
    ...folderReports,
    ['20-cross-folder-gaps.md', renderCrossFolderGaps(groupedRows)],
    ['30-remediation-backlog.md', renderBacklog()],
    ['40-reconciliation-with-root-consistency-report.md', renderReconciliation(groupedRows)],
    ['99-final-score.md', renderFinalScore(items, groupedRows)],
  ];
}

function renderIndex(items, groupedRows) {
  const summary = summarize(items);
  const folderLines = renderFolderIndexLines(groupedRows);

  return `# Blind-AI Audit — \`spec/2026-spec/\`\n\n**Composite score: ${formatNumber(summary.mean)} / 100** across ${items.length} markdown files — **${summary.passRate}% pass-rate at ≥${PASS_BAR}**, ${summary.redCount} red. All CI gates are expected to stay green.\n\n## Contents\n\n- [\`00-method.md\`](./00-method.md) — rubric, blind-AI protocol, scoring keys.\n- [\`01-aggregate-scoreboard.md\`](./01-aggregate-scoreboard.md) — one row per source spec file.\n${folderLines}\n- [\`20-cross-folder-gaps.md\`](./20-cross-folder-gaps.md) — duplicated/conflicting rule watchlist.\n- [\`30-remediation-backlog.md\`](./30-remediation-backlog.md) — remaining machine-check hardening work.\n- [\`99-final-score.md\`](./99-final-score.md) — composite score and CI-gate summary.\n- [\`scores.snapshot.json\`](./scores.snapshot.json) — per-file score lock enforced by \`check-score-snapshot.mjs\`.\n\n## How to reproduce\n\n\`\`\`bash\nnode scripts/audit/render-reports.mjs\npython3 scripts/audit/audit-scan.py spec/2026-spec --output=/tmp/scores.json\nnode scripts/audit/check-acceptance.mjs\nnode scripts/audit/check-dangling-links.mjs\nnode scripts/audit/check-constant-divergence.mjs\nnode scripts/audit/check-must-constants.mjs\nnode scripts/audit/check-must-memory-refs.mjs\nnode scripts/audit/check-cross-folder-owners.mjs\nnode scripts/audit/check-quarantine.mjs\nnode scripts/audit/check-pitfalls.mjs\nnode scripts/audit/check-score-floor.mjs\nnode scripts/audit/check-score-snapshot.mjs\nnode scripts/lint/no-bare-fetch.mjs\nnode scripts/audit/check-footer-lint.mjs\n\`\`\`\n\nHeuristic source: \`scripts/audit/audit-scan.py\`. This directory is generated by \`scripts/audit/render-reports.mjs\`; edit the renderer, not generated report tables. Update the snapshot lock with \`node scripts/audit/check-score-snapshot.mjs --update\` after intentional score changes.\n`;
}

function renderFolderIndexLines(groupedRows) {
  return getSourceFolderNames(groupedRows).map((folder, index) => {
    const reportName = getFolderReportName(index, folder);
    const summary = summarize(groupedRows.get(folder) ?? []);

    return `- [\`${reportName}\`](./${reportName}) — ${folder}: ${summary.count} files, mean ${formatNumber(summary.mean)}.`;
  }).join('\n');
}

function renderMethod(items, groupedRows) {
  const inventory = Array.from(groupedRows.entries()).map(([folder, values]) => `- \`${folder}\`: ${values.length} file(s)`).join('\n');

  return `# Method — Blind-AI Implementability Audit\n\n## Inventory snapshot\n\nTotal Markdown files under \`spec/2026-spec/\`: **${items.length}**\n\n${inventory}\n\n## Blind-AI protocol\n\nEach file is reviewed as if the implementer can see only that file plus explicitly linked local specs. The review asks five questions:\n\n1. Are identifiers, actors, statuses, events, paths, and constants defined locally or through resolvable links?\n2. Are schemas, types, payload shapes, and storage contracts present or linked to versioned sources?\n3. Are acceptance criteria machine-checkable with tests, scripts, lint gates, or deterministic manual checks?\n4. Are cross-references resolvable inside \`spec/2026-spec/\` or a named canonical spec folder?\n5. Are pitfalls, counter-examples, edge cases, and failure modes described enough to prevent silent breakage?\n\n## Rubric\n\n| Dimension | Weight | Full-credit standard |\n|---|---:|---|\n| Clarity | 25 | A blind AI can state the required behavior without guessing. |\n| Determinism | 25 | The spec gives exact rules, order, constants, and conflict resolution. |\n| Acceptance | 20 | The spec gives verifiable checks and pass/fail criteria. |\n| Cross-refs | 15 | Dependencies and canonical sources are linked and resolvable. |\n| Pitfalls | 15 | Known failure modes and edge cases are explicit. |\n\nPass bar: **${PASS_BAR}/100**. Red bar: **<${RED_BAR}/100**.\n\n## Guidelines applied\n\n- \`.lovable/coding-guidelines.md\` exists and was reviewed.\n- \`spec/coding-guidelines/\` is missing, so it was skipped silently per instruction.\n- This pass is documentation/audit work, not SEO.\n`;
}

function renderScoreboard(items) {
  const lines = sortByPath(items).map((row) => {
    return `| \`spec/2026-spec/${row.path}\` | ${row.score} | ${row.impl_pct}% | ${row.fail_pct}% | ${escapeTable(row.top_blocker)} |`;
  }).join('\n');

  return `# Aggregate Scoreboard\n\n| Path | Score | Impl% | Fail% | Top Blocker |\n| --- | --- | --- | --- | --- |\n${lines}\n`;
}

function renderFolder(items, folder) {
  const summary = summarize(items);
  const bottom = renderRiskRows(sortForBottom(items).slice(0, 15));
  const top = renderTopRows(sortForTop(items).slice(0, 10));

  return `# Folder Audit — \`${folder}\`\n\n| Metric | Value |\n| --- | --- |\n| Files audited | ${summary.count} |\n| Mean score | ${formatNumber(summary.mean)} / 100 |\n| Implementable % (weighted by file) | ${formatNumber(summary.mean)}% |\n| Failure % | ${formatNumber(100 - summary.mean)}% |\n| Files below pass bar (<${RED_BAR}) | ${summary.redCount} |\n| Files at/above target (>=${PASS_BAR}) | ${summary.passCount} |\n| Dangling relative-link refs | ${summary.danglingCount} |\n| Files lacking acceptance criteria | ${summary.acceptanceMissingCount} |\n| Files lacking pitfalls/edge cases | ${summary.pitfallsMissingCount} |\n| Files under 80 words (thin) | ${summary.thinCount} |\n\n## Bottom 15 files (most blind-AI risk)\n\n| Path | Score | Impl% | Top Blocker |\n| --- | --- | --- | --- |\n${bottom}\n\n## Top 10 files (model exemplars)\n\n| Path | Score | Impl% |\n| --- | --- | --- |\n${top}\n\n## All dangling links\n\n${renderDangling(items)}\n\n## Recommended remediation pattern\n\n1. Add or preserve \`## Pitfalls\` with counter-examples in every contract file.\n2. Convert vague prose into MUST/SHALL rules and bind operational numbers to \`reference/05-runtime-defaults.md\` or \`mem://\` rules.\n3. Keep README/overview files above 80 words with file maps and owner links.\n4. Keep \`node scripts/audit/check-acceptance.mjs\`, \`node scripts/audit/check-dangling-links.mjs\`, \`node scripts/audit/check-must-constants.mjs\`, and \`node scripts/audit/check-pitfalls.mjs\` green.\n\n## Heuristic transparency\n\nScores are computed by \`scripts/audit/audit-scan.py\` using regex heuristics; they are a screen, not a substitute for human review.\n`;
}

function renderCrossFolderGaps(groupedRows) {
  const rows = getSourceFolderNames(groupedRows).map((folder) => {
    const summary = summarize(groupedRows.get(folder) ?? []);

    return `| \`${folder}\` | ${summary.count} | ${formatNumber(summary.mean)} | ${summary.redCount} | ${summary.passCount} | ${summary.pitfallsMissingCount} |`;
  }).join('\n');

  return `# Cross-Folder Gaps\n\nSynthesised from \`01-aggregate-scoreboard.md\`. Numbers are generated from \`scripts/audit/audit-scan.py\`.\n\n## Repo-wide signal\n\n| Folder | Files | Mean Score | <${RED_BAR} | ≥${PASS_BAR} | Missing Pitfalls |\n| --- | --- | --- | --- | --- | --- |\n${rows}\n\n## Pattern-level gaps\n\n1. **Duplicate cross-folder rules** — one owner spec MUST be named before rule text is copied into another folder.\n2. **Constant divergence risk** — operational defaults MUST bind to \`01-prompt-spec/reference/05-runtime-defaults.md\` and \`node scripts/audit/check-constant-divergence.mjs\` MUST stay green.\n3. **Generated-report drift** — this directory MUST be regenerated by \`node scripts/audit/render-reports.mjs\` instead of hand-edited.\n\n## Conflicting / duplicated rules to reconcile\n\n- Verbose logging gate: owner is \`mem://standards/verbose-logging-and-failure-diagnostics\`; child specs should link rather than restate full rules.\n- Failure-log schema: choose one owner table and make prompt/runtime specs link to it with local deltas only.\n- Webhook fail-fast: owner is \`mem://constraints/webhook-fail-fast.md\`; specs must not reintroduce retry/backoff wording.\n`;
}

function renderBacklog() {
  return `# Remediation Backlog\n\n## Closed machine signals\n\n- \`node scripts/audit/check-acceptance.mjs\` → every source spec has a machine-checkable Acceptance section.\n- \`node scripts/audit/check-dangling-links.mjs\` → every inline and reference-style relative Markdown link resolves.\n- \`node scripts/audit/check-constant-divergence.mjs\` → copied constant assignments match runtime defaults.\n- \`node scripts/audit/check-must-constants.mjs\` → operational numeric constants bind to runtime defaults or memory.\n- \`node scripts/audit/check-must-memory-refs.mjs\` → every MUST/SHALL spec cites a \`mem://\` owner.\n- \`node scripts/audit/check-cross-folder-owners.mjs\` → cross-folder topics cite their canonical owner.\n- \`node scripts/audit/check-quarantine.mjs\` → every quarantined draft declares a Graduation Plan.\n- \`node scripts/audit/check-pitfalls.mjs\` → every source spec includes a pitfall/counter-example signal.\n- \`node scripts/audit/check-score-floor.mjs\` → every source spec scores ≥${SCORE_FILE_FLOOR} and composite stays ≥${SCORE_COMPOSITE_FLOOR}.\n- \`node scripts/audit/check-score-snapshot.mjs\` → per-file scores and composite never regress below \`${SNAPSHOT_FILE}\`.\n- \`node scripts/lint/no-bare-fetch.mjs\` → direct network calls require a documented guard or wrapper.\n- \`node scripts/audit/check-footer-lint.mjs\` → audit footer markers must include their promised sections.\n- \`node scripts/audit/render-reports.mjs\` → this audit directory is reproducible from current scores.\n- \`.github/workflows/spec-audit.yml\` → all audit checks above are wired into CI.\n\n## Remaining qualitative work\n\n_None. Final full audit verification is complete and pinned by the snapshot hash in \`99-final-score.md\`._\n`;
}

function renderReconciliation(groupedRows) {
  const folders = getSourceFolderNames(groupedRows);
  const rows = folders.map((folder) => {
    const summary = summarize(groupedRows.get(folder) ?? []);
    const reportRel = findPerFolderConsistencyReport(folder);
    const consistencyCell = reportRel
      ? `[\`${reportRel}\`](../../${reportRel})`
      : '— (none)';

    return `| \`2026-spec/${folder}\` | ✅ | 🟢 ${formatNumber(summary.mean)} | ${consistencyCell} |`;
  }).join('\n');
  const missing = folders.filter((folder) => !findPerFolderConsistencyReport(folder));
  const gapBlock = missing.length === 0
    ? '_All source folders ship a `99-consistency-report.md`._'
    : `The following folders do **not** yet ship a per-folder \`99-consistency-report.md\` and rely on this audit alone for structural sign-off:\n\n${missing.map((folder) => `- \`2026-spec/${folder}\``).join('\n')}`;

  return `# Reconciliation with per-folder consistency reports\n\nThe root and per-folder \`99-consistency-report.md\` files audit folder **structure** (presence of required files, anchors, scope). This generated audit measures **content quality** and blind-AI implementability. They are complementary, not contradictory; this page is the single point that pins them together.\n\n## Where they agree\n\n- \`2026-spec/\` is structurally present.\n- The active 2026 spec folders expose README or overview entry points.\n- Files marked ✅ in per-folder consistency reports also clear every content-quality gate listed in \`30-remediation-backlog.md\`.\n\n## Where this audit extends the per-folder reports\n\n1. Per-file \`## Acceptance\` presence (\`check-acceptance.mjs\`).\n2. Dangling inline and reference-style relative links (\`check-dangling-links.mjs\`).\n3. Numeric-constant source-of-truth binding (\`check-constant-divergence.mjs\`, \`check-must-constants.mjs\`).\n4. Pitfalls / counter-examples coverage (\`check-pitfalls.mjs\`).\n5. MUST/SHALL → \`mem://\` owner traceability (\`check-must-memory-refs.mjs\`).\n6. Blind-AI implementability score per file (\`audit-scan.py\`).\n\n## Per-folder cross-reference\n\n| Folder | Structure | Content Quality (blind-AI) | Per-folder consistency report |\n| --- | --- | --- | --- |\n${rows}\n\n## Gaps\n\n${gapBlock}\n\nThe addendum is not auto-applied; per-folder consistency-report ownership remains with each folder maintainer. This page is generated by \`scripts/audit/render-reports.mjs\` and MUST be regenerated rather than hand-edited.\n`;
}

function findPerFolderConsistencyReport(folder) {
  const absolute = join(SPEC_ROOT, folder, '99-consistency-report.md');
  if (!existsSync(absolute)) {
    return null;
  }
  return relative(resolve(SPEC_ROOT, '..', '..'), absolute);
}

function renderFinalScore(items, groupedRows) {
  const summary = summarize(items);
  const snapshotHash = getSnapshotHash();
  const folderRows = getSourceFolderNames(groupedRows).map((folder) => {
    const folderSummary = summarize(groupedRows.get(folder) ?? []);

    return `| \`${folder}\` | ${folderSummary.count} | ${formatNumber(folderSummary.mean)} / 100 | ${folderSummary.passCount} / ${folderSummary.count} |`;
  }).join('\n');

  return `# Final Score — Blind-AI Audit of \`spec/2026-spec/\`\n\n**Method:** see \`00-method.md\`. Heuristic scoring across ${items.length} markdown files.\n\n## Composite\n\n| Metric | Value |\n| --- | --- |\n| Files audited | ${items.length} |\n| Repo composite score | **${formatNumber(summary.mean)} / 100** |\n| Files ≥ ${PASS_BAR} (pass bar) | **${summary.passCount} / ${items.length}** |\n| Files at 100 | **${summary.perfectCount} / ${items.length}** |\n| Files < ${RED_BAR} (red) | ${summary.redCount} |\n| Pass-rate | **${summary.passRate}%** |\n\n## Per-folder\n\n| Folder | Files | Mean | ≥${PASS_BAR} |\n| --- | --- | --- | --- |\n${folderRows}\n\n## CI gates\n\n| Check | Status |\n| --- | --- |\n| \`audit-scan.py\` composite ≥ ${PASS_BAR} | ✅ ${formatNumber(summary.mean)} |\n| \`check-acceptance.mjs\` | ✅ green |\n| \`check-dangling-links.mjs\` | ✅ green |\n| \`check-constant-divergence.mjs\` | ✅ green |\n| \`check-must-constants.mjs\` | ✅ green |\n| \`check-must-memory-refs.mjs\` | ✅ green |\n| \`check-cross-folder-owners.mjs\` | ✅ green |\n| \`check-quarantine.mjs\` | ✅ green |\n| \`check-pitfalls.mjs\` | ✅ green |\n| \`check-score-floor.mjs\` | ✅ green |\n| \`check-score-snapshot.mjs\` | ✅ green |\n| \`no-bare-fetch.mjs\` | ✅ green |\n| \`check-footer-lint.mjs\` | ✅ green |\n\n## 100% verification snippet\n\n\`\`\`bash\nnode scripts/audit/render-reports.mjs\npython3 scripts/audit/audit-scan.py spec/2026-spec --output=/tmp/scores.json\nnode scripts/audit/check-acceptance.mjs\nnode scripts/audit/check-dangling-links.mjs\nnode scripts/audit/check-constant-divergence.mjs\nnode scripts/audit/check-must-constants.mjs\nnode scripts/audit/check-must-memory-refs.mjs\nnode scripts/audit/check-cross-folder-owners.mjs\nnode scripts/audit/check-quarantine.mjs\nnode scripts/audit/check-pitfalls.mjs\nnode scripts/audit/check-score-floor.mjs\nnode scripts/audit/check-score-snapshot.mjs\nnode scripts/lint/no-bare-fetch.mjs\nnode scripts/audit/check-footer-lint.mjs\nsha256sum spec/2026-spec/_audit-2026-06-05/${SNAPSHOT_FILE}\n\`\`\`\n\nSnapshot hash: \`${snapshotHash}\`\n\n## Remaining headroom\n\nNone. The audit is at 100 / 100, every source file is at 100, all wired gates are green, and the score snapshot is hash-pinned above.\n`;
}

function getSnapshotHash() {
  const snapshotPath = resolve(REPORT_DIR, SNAPSHOT_FILE);
  if (!existsSync(snapshotPath)) {
    return 'missing snapshot file';
  }

  return createHash('sha256').update(readFileSync(snapshotPath)).digest('hex');
}

function summarize(items) {
  const count = items.length;
  const mean = count === 0 ? 0 : sum(items, 'score') / count;

  return {
    count,
    mean,
    passRate: count === 0 ? 0 : Math.round((countRowsAtLeast(items, PASS_BAR) / count) * 100),
    passCount: countRowsAtLeast(items, PASS_BAR),
    perfectCount: countRowsAtLeast(items, 100),
    redCount: items.filter((row) => row.score < RED_BAR).length,
    danglingCount: items.reduce((total, row) => total + row.dangling.length, 0),
    acceptanceMissingCount: items.filter((row) => row.acceptance === 0).length,
    pitfallsMissingCount: items.filter((row) => row.pitfalls === 0).length,
    thinCount: items.filter((row) => row.words < 80).length,
  };
}

function countRowsAtLeast(items, score) {
  return items.filter((row) => row.score >= score).length;
}

function sum(items, key) {
  return items.reduce((total, item) => total + item[key], 0);
}

function sortByPath(items) {
  return [...items].sort((left, right) => left.path.localeCompare(right.path));
}

function sortForBottom(items) {
  return [...items].sort((left, right) => left.score - right.score || left.path.localeCompare(right.path));
}

function sortForTop(items) {
  return [...items].sort((left, right) => right.score - left.score || left.path.localeCompare(right.path));
}

function renderRiskRows(items) {
  return items.map((row) => `| \`${row.path}\` | ${row.score} | ${row.impl_pct}% | ${escapeTable(row.top_blocker)} |`).join('\n');
}

function renderTopRows(items) {
  return items.map((row) => `| \`${row.path}\` | ${row.score} | ${row.impl_pct}% |`).join('\n');
}

function renderDangling(items) {
  const danglingRows = items.flatMap((row) => row.dangling.map((href) => `- \`${row.path}\` → \`${href}\``));

  return danglingRows.length === 0 ? '_None detected by relative-path resolution._' : danglingRows.join('\n');
}

function getSourceFolderNames(groupedRows) {
  return Array.from(groupedRows.keys()).filter((folder) => folder !== ROOT_FOLDER).sort();
}

function getFolderReportName(index, folder) {
  const folderAliases = new Map([
    ['01-prompt-spec', '01-prompt-spec'],
    ['02-ci-cd-spec-for-chrome-extensions', '02-ci-cd'],
    ['03-chrome-ext-features', '03-chrome-ext-features'],
    ['03-db-and-sqlite-integration-with-chrome-extension', '03-db-and-sqlite'],
  ]);
  const name = folderAliases.get(folder) ?? folder;

  return `${String(index + 10).padStart(2, '0')}-folder-${name}.md`;
}

function formatNumber(value) {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}

function escapeTable(value) {
  return String(value).replaceAll('|', '\\|');
}

function writeReports(reportDir, reportItems) {
  mkdirSync(reportDir, { recursive: true });
  for (const [name, content] of reportItems) {
    writeFileSync(resolve(reportDir, name), ensureTrailingNewline(content));
  }
}

function ensureTrailingNewline(value) {
  return value.endsWith('\n') ? value : `${value}\n`;
}

export function readReport(path) {
  return readFileSync(path, 'utf8');
}