/**
 * diagnostic-toast-telemetry.ts (v4.298.0)
 *
 * Structured emission for every diagnostic toast surfaced by
 * `showDiagnosticToast`. Every event carries the diagnostic `code`, the
 * mapped toast `level`, and a redacted snapshot of any `requestDetail`
 * that the caller attached so a support engineer can correlate a user
 * report ("I saw code=RENAME_AUTH_RECOVERY_E001") with the exact HTTP
 * op / status / URL without paging through raw console output.
 *
 * Emission surfaces (all best-effort, never throw to callers):
 *   1. `log('[DiagnosticToast:<code>] ...', level)` for the activity log
 *   2. `localStorage[StorageKey.DiagnosticToastTrace]` bounded ring buffer
 *   3. `window.dispatchEvent(new CustomEvent('marco:diagnostic-toast'))`
 *      so tests / dev tools / audit panels can subscribe without patching.
 *
 * Mirrors the shape of `prompt-seed-telemetry.ts` on purpose so operators
 * only have to learn one telemetry contract.
 */

import { log } from '../logger';
import { logError } from '../error-utils';
import { StorageKey } from '../types/storage-keys';
import type { ErrorCode, ErrorSeverity } from '../errors/error-codes';
import type { ToastLevel } from '../errors/show-diagnostic-toast';
import type { RequestDetail, ToastOpts } from '../toast';

export const DIAGNOSTIC_TOAST_TRACE_MAX = 50;

export interface RequestDetailSnapshot {
  op?: string;
  method?: string;
  url?: string;
  status?: number;
  statusText?: string;
  /** Byte length of body/responseBody, never the raw text (may hold tokens). */
  bodyBytes?: number;
  responseBodyBytes?: number;
  /** Header names only; values are redacted (may include Authorization). */
  headerNames?: string[];
  /** End-to-end correlation id copied verbatim from the request context. */
  correlationId?: string;
}

export interface DiagnosticToastEvent {
  /** ISO timestamp (UTC — see mem://localization/timezone). */
  at: string;
  code: ErrorCode | string;
  severity: ErrorSeverity;
  level: ToastLevel;
  title: string;
  /** Truthy when caller passed `{ noStop: true }`. */
  noStop: boolean;
  /**
   * End-to-end correlation id for this failure. Copied from
   * `opts.requestDetail.correlationId` when the caller supplied one;
   * otherwise auto-generated by `showDiagnosticToast` so every event
   * carries a traceable id and stays joinable across log surfaces.
   */
  correlationId: string;
  requestDetail?: RequestDetailSnapshot;
  /** Free-form context (call site tag). */
  detail?: string;
}

export interface EmitDiagnosticToastInput {
  code: ErrorCode | string;
  severity: ErrorSeverity;
  level: ToastLevel;
  title: string;
  opts?: ToastOpts | undefined;
  detail?: string;
  /**
   * Optional pre-computed correlation id. When omitted the emitter
   * falls back to `opts.requestDetail.correlationId` and finally to a
   * freshly-generated id via `generateCorrelationId()`.
   */
  correlationId?: string;
}


function redactRequestDetail(rd: RequestDetail | undefined): RequestDetailSnapshot | undefined {
  if (!rd) return undefined;
  const snap: RequestDetailSnapshot = {};
  if (rd.op !== undefined) snap.op = rd.op;
  if (rd.method !== undefined) snap.method = rd.method;
  if (rd.url !== undefined) snap.url = rd.url;
  if (rd.status !== undefined) snap.status = rd.status;
  if (rd.statusText !== undefined) snap.statusText = rd.statusText;
  if (typeof rd.body === 'string') snap.bodyBytes = rd.body.length;
  if (typeof rd.responseBody === 'string') snap.responseBodyBytes = rd.responseBody.length;
  if (rd.headers) snap.headerNames = Object.keys(rd.headers);
  if (typeof rd.correlationId === 'string' && rd.correlationId.length > 0) {
    snap.correlationId = rd.correlationId;
  }
  return snap;
}

/**
 * Generate an opaque, URL-safe correlation id. The `dtx-` prefix marks
 * events sourced by the diagnostic-toast pipeline; the `<epoch>-<rand>`
 * suffix mirrors the shape already used by `auth-bridge.requestId` and
 * `extension-relay.requestId` so operators only have to learn one format.
 */
export function generateCorrelationId(): string {
  return 'dtx-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 10);
}

function resolveCorrelationId(input: EmitDiagnosticToastInput): string {
  if (typeof input.correlationId === 'string' && input.correlationId.length > 0) {
    return input.correlationId;
  }
  const rdId = input.opts?.requestDetail?.correlationId;
  if (typeof rdId === 'string' && rdId.length > 0) return rdId;
  return generateCorrelationId();
}

function formatLine(evt: DiagnosticToastEvent): string {
  const parts: string[] = [
    'code=' + evt.code,
    'severity=' + evt.severity,
    'level=' + evt.level,
    'cid=' + evt.correlationId,
  ];
  if (evt.noStop) parts.push('noStop=true');
  const rd = evt.requestDetail;
  if (rd) {
    if (rd.op) parts.push('op=' + rd.op);
    if (rd.method) parts.push('method=' + rd.method);
    if (rd.status !== undefined) parts.push('status=' + String(rd.status));
    if (rd.url) parts.push('url=' + rd.url);
  }
  if (evt.detail) parts.push('detail=' + evt.detail);
  return '[DiagnosticToast] ' + parts.join(' ');
}


function levelToLogLevel(level: ToastLevel): 'success' | 'warning' | 'error' | 'info' {
  if (level === 'error') return 'error';
  if (level === 'warn') return 'warning';
  return 'info';
}

function appendToTraceBuffer(evt: DiagnosticToastEvent): void {
  try {
    const raw = localStorage.getItem(StorageKey.DiagnosticToastTrace);
    const parsed = raw ? (JSON.parse(raw) as unknown) : [];
    const buf: DiagnosticToastEvent[] = Array.isArray(parsed)
      ? (parsed as DiagnosticToastEvent[])
      : [];
    buf.push(evt);
    while (buf.length > DIAGNOSTIC_TOAST_TRACE_MAX) buf.shift();
    localStorage.setItem(StorageKey.DiagnosticToastTrace, JSON.stringify(buf));
  } catch (err) {
    logError('DiagnosticToastTelemetry', 'appendToTraceBuffer failed', err);
  }
}

function dispatchWindowEvent(evt: DiagnosticToastEvent): void {
  try {
    if (typeof window === 'undefined' || typeof window.dispatchEvent !== 'function') return;
    window.dispatchEvent(new CustomEvent('marco:diagnostic-toast', { detail: evt }));
  } catch (err) {
    logError('DiagnosticToastTelemetry', 'dispatchWindowEvent failed', err);
  }
}

/**
 * Emit a structured diagnostic-toast event. Never throws. Returns the
 * event that was emitted so callers/tests can assert its shape.
 */
export function emitDiagnosticToastEvent(input: EmitDiagnosticToastInput): DiagnosticToastEvent {
  const correlationId = resolveCorrelationId(input);
  const evt: DiagnosticToastEvent = {
    at: new Date().toISOString(),
    code: input.code,
    severity: input.severity,
    level: input.level,
    title: input.title,
    noStop: input.opts?.noStop === true,
    correlationId: correlationId,
  };
  const rd = redactRequestDetail(input.opts?.requestDetail);
  if (rd) {
    // Ensure the snapshot always carries the same id as the event, even
    // when the caller-supplied requestDetail did not include one.
    if (!rd.correlationId) rd.correlationId = correlationId;
    evt.requestDetail = rd;
  }
  if (input.detail !== undefined) evt.detail = input.detail;
  try {
    log(formatLine(evt), levelToLogLevel(evt.level));
  } catch (err) {
    logError('DiagnosticToastTelemetry', 'log() emit failed', err);
  }
  appendToTraceBuffer(evt);
  dispatchWindowEvent(evt);
  return evt;
}


/** Read the trace ring buffer for tests / debug panels. */
export function readDiagnosticToastTrace(): DiagnosticToastEvent[] {
  try {
    const raw = localStorage.getItem(StorageKey.DiagnosticToastTrace);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as unknown;
    return Array.isArray(parsed) ? (parsed as DiagnosticToastEvent[]) : [];
  } catch (err) {
    logError('DiagnosticToastTelemetry', 'readDiagnosticToastTrace failed', err);
    return [];
  }
}

/** Clear the trace buffer (test helper). */
export function clearDiagnosticToastTrace(): void {
  try {
    localStorage.removeItem(StorageKey.DiagnosticToastTrace);
  } catch (err) {
    logError('DiagnosticToastTelemetry', 'clearDiagnosticToastTrace failed', err);
  }
}
