#!/usr/bin/env node
/**
 * clean-build.mjs — Force-fresh build by purging every cache layer
 *
 * Why this exists
 * ---------------
 * Repeated cached builds occasionally surface phantom "missing file" errors
 * because a stale `.cache/standalone-builds/<name>/<hash>/dist/` snapshot is
 * restored on top of a working tree where the source file was renamed or
 * deleted. The cache key is content-hashed, so this only happens when an
 * input slips outside the hash window (e.g. a shared dep added without an
 * `--extra-input=` flag, or a stale `*.tsbuildinfo` masking a fresh tsc
 * error). When a developer sees a "missing file" error they can't reproduce
 * after `git status` shows clean, this script is the escape hatch.
 *
 * What it clears (sequential, fail-fast — no retry/backoff per Core policy)
 * -----------------------------------------------------------------------
 *   1. .cache/standalone-builds/         (cached-build.mjs snapshots)
 *   2. .cache/tsbuildinfo/               (incremental tsc state)
 *   3. *.tsbuildinfo at repo root        (root tsc incremental state)
 *   4. node_modules/.vite/               (vite dep pre-bundle cache)
 *   5. node_modules/.cache/              (any other tool caches)
 *   6. standalone-scripts/<name>/dist/   (stale bundle outputs)
 *   7. dist/                             (root vite output)
 *
 * What it does NOT touch
 * ----------------------
 *   - node_modules/ (everything except the cache subdirs above)
 *   - skipped/ and .release/ (read-only per Core policy)
 *   - any source files, configs, or generated instruction.json artifacts
 *     (those are regenerated by the next build step anyway)
 *
 * Usage
 * -----
 *   node scripts/clean-build.mjs                 # clear caches only
 *   node scripts/clean-build.mjs --dry-run       # print what would be removed
 *   pnpm run clean                               # alias for clear-only
 *   pnpm run build:clean                         # clean then full extension build
 *   pnpm run build:standalone:clean              # clean then standalone build
 *
 * Environment
 * -----------
 *   STANDALONE_BUILD_NO_CACHE=1 is exported for the rest of the process
 *   chain so cached-build.mjs treats every project as a miss even if its
 *   snapshot somehow survives (defence in depth).
 *
 * Author: Riseup Asia LLC
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..");
const DRY_RUN = process.argv.includes("--dry-run");

/** Targets are repo-relative. Each is removed if it exists. */
const STATIC_TARGETS = [
    ".cache/standalone-builds",
    ".cache/tsbuildinfo",
    "node_modules/.vite",
    "node_modules/.cache",
    "dist",
    "tsconfig.node.tsbuildinfo",
    "tsconfig.app.tsbuildinfo",
];

/** Standalone projects whose `dist/` should be wiped. Mirrors PROJECTS in build-standalone.mjs. */
const STANDALONE_PROJECTS = [
    "marco-sdk",
    "xpath",
    "macro-controller",
    "payment-banner-hider",
    "lovable-common",
    "lovable-owner-switch",
    "lovable-user-add",
];

function rel(p) {
    return path.relative(REPO_ROOT, p) || ".";
}

function removePath(absPath) {
    if (!fs.existsSync(absPath)) {
        console.log(`  ·  skip (absent)        ${rel(absPath)}`);
        return { removed: false, reason: "absent" };
    }
    if (DRY_RUN) {
        console.log(`  ·  would remove         ${rel(absPath)}`);
        return { removed: false, reason: "dry-run" };
    }
    fs.rmSync(absPath, { recursive: true, force: true });
    console.log(`  ✓  removed              ${rel(absPath)}`);
    return { removed: true, reason: "ok" };
}

function main() {
    const banner = DRY_RUN
        ? "[clean-build] DRY RUN — no files will be removed"
        : "[clean-build] purging cache + stale dist outputs";
    console.log(banner);
    console.log("");

    let removed = 0;
    let skipped = 0;

    console.log("[1/2] Static cache targets:");
    for (const target of STATIC_TARGETS) {
        const result = removePath(path.join(REPO_ROOT, target));
        if (result.removed) removed++;
        else skipped++;
    }

    console.log("");
    console.log("[2/2] Standalone project dist/ folders:");
    for (const proj of STANDALONE_PROJECTS) {
        const result = removePath(path.join(REPO_ROOT, "standalone-scripts", proj, "dist"));
        if (result.removed) removed++;
        else skipped++;
    }

    console.log("");
    if (DRY_RUN) {
        console.log("[clean-build] dry run complete. Re-run without --dry-run to apply.");
    } else {
        console.log(`[clean-build] done. removed=${removed} skipped=${skipped}`);
        console.log("[clean-build] next build will be a guaranteed cache miss.");
    }
}

main();
