/**
 * Run Statistics Dashboard — Spec 15 T-7 + T-9
 *
 * Shows macro loop cycle stats: totals, success rate,
 * average duration, last error, mini bar chart, and session export.
 */

import { useRunStats, type CycleMetric, type RunStats } from "@/hooks/use-run-stats";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RefreshCw, Trash2, Activity, CheckCircle2, XCircle, SkipForward, Clock, AlertTriangle, FileDown, ClipboardCopy } from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { toast } from "sonner";

/* ------------------------------------------------------------------ */
/*  Markdown Report Generator (T-9)                                    */
/* ------------------------------------------------------------------ */

function generateMarkdownReport(stats: RunStats): string {
    const now = new Date();
    const date = now.toISOString().replace("T", " ").slice(0, 16);

    const errorCycles = stats.recentCycles.filter(c => c.status === "error");

    let md = `# Marco Session Report\n`;
    md += `- **Date**: ${date}\n`;
    md += `- **Cycles**: ${stats.totalCycles} total (${stats.successCount} success, ${stats.errorCount} errors, ${stats.skippedCount} skipped)\n`;
    md += `- **Success Rate**: ${stats.successRate}%\n`;
    md += `- **Avg Duration**: ${stats.avgDurationMs}ms\n`;
    md += `\n`;

    if (errorCycles.length > 0) {
        md += `## Errors\n\n`;
        md += `| Cycle | Time | Error |\n`;
        md += `|-------|------|-------|\n`;
        errorCycles.forEach(c => {
            const time = new Date(c.startTime).toLocaleTimeString();
            md += `| ${c.cycleNumber} | ${time} | ${c.errorMessage ?? "Unknown error"} |\n`;
        });
        md += `\n`;
    }

    if (stats.recentCycles.length > 0) {
        md += `## Recent Cycles (last ${stats.recentCycles.length})\n\n`;
        md += `| # | Status | Duration | Time |\n`;
        md += `|---|--------|----------|------|\n`;
        stats.recentCycles.forEach(c => {
            const time = new Date(c.startTime).toLocaleTimeString();
            md += `| ${c.cycleNumber} | ${c.status} | ${c.durationMs}ms | ${time} |\n`;
        });
        md += `\n`;
    }

    md += `---\n*Generated by Marco Extension*\n`;
    return md;
}

function downloadMarkdown(content: string) {
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `marco-session-report-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
}

/* ------------------------------------------------------------------ */
/*  Stat Card                                                          */
/* ------------------------------------------------------------------ */

function StatCard({ label, value, icon: Icon, color }: {
    label: string;
    value: string | number;
    icon: typeof Activity;
    color: string;
}) {
    return (
        <div className="flex items-center gap-3 rounded-lg border border-border bg-card p-3">
            <div className={`flex h-9 w-9 items-center justify-center rounded-md ${color}`}>
                <Icon className="h-4 w-4 text-primary-foreground" />
            </div>
            <div>
                <p className="text-xs text-muted-foreground">{label}</p>
                <p className="text-lg font-bold">{value}</p>
            </div>
        </div>
    );
}

/* ------------------------------------------------------------------ */
/*  Mini Bar Chart                                                     */
/* ------------------------------------------------------------------ */

const STATUS_COLORS: Record<string, string> = {
    success: "bg-emerald-500",
    error: "bg-destructive",
    skipped: "bg-muted-foreground",
};

function MiniBarChart({ cycles }: { cycles: CycleMetric[] }) {
    if (cycles.length === 0) {
        return (
            <p className="text-xs text-muted-foreground italic py-2">
                No cycles recorded yet.
            </p>
        );
    }

    return (
        <TooltipProvider>
            <div className="flex items-end gap-0.5 h-10">
                {cycles.map((c, i) => {
                    const maxDur = Math.max(...cycles.map(x => x.durationMs), 1);
                    const heightPct = Math.max(15, (c.durationMs / maxDur) * 100);
                    return (
                        <Tooltip key={i}>
                            <TooltipTrigger asChild>
                                <div
                                    className={`w-2.5 rounded-t-sm transition-all ${STATUS_COLORS[c.status] ?? "bg-muted"}`}
                                    style={{ height: `${heightPct}%` }}
                                />
                            </TooltipTrigger>
                            <TooltipContent side="top" className="text-xs">
                                <p>Cycle #{c.cycleNumber}</p>
                                <p>{c.status} — {c.durationMs}ms</p>
                                {c.errorMessage && <p className="text-destructive">{c.errorMessage}</p>}
                            </TooltipContent>
                        </Tooltip>
                    );
                })}
            </div>
        </TooltipProvider>
    );
}

/* ------------------------------------------------------------------ */
/*  Panel                                                              */
/* ------------------------------------------------------------------ */

// eslint-disable-next-line max-lines-per-function
export function RunStatsPanel() {
    const { stats, loading, refresh, clear } = useRunStats();

    const handleCopyReport = () => {
        if (!stats) return;
        const md = generateMarkdownReport(stats);
        navigator.clipboard.writeText(md);
        toast.success("Report copied to clipboard");
    };

    const handleDownloadReport = () => {
        if (!stats) return;
        const md = generateMarkdownReport(stats);
        downloadMarkdown(md);
        toast.success("Report downloaded");
    };

    return (
        <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-semibold flex items-center gap-2">
                    <Activity className="h-4 w-4 text-primary" />
                    Run Statistics
                </CardTitle>
                <div className="flex gap-1">
                    <Tooltip>
                        <TooltipProvider>
                            <TooltipTrigger asChild>
                                <Button variant="ghost" size="icon" className="h-7 w-7" onClick={handleCopyReport} disabled={!stats || stats.totalCycles === 0}>
                                    <ClipboardCopy className="h-3.5 w-3.5" />
                                </Button>
                            </TooltipTrigger>
                            <TooltipContent>Copy report to clipboard</TooltipContent>
                        </TooltipProvider>
                    </Tooltip>
                    <Tooltip>
                        <TooltipProvider>
                            <TooltipTrigger asChild>
                                <Button variant="ghost" size="icon" className="h-7 w-7" onClick={handleDownloadReport} disabled={!stats || stats.totalCycles === 0}>
                                    <FileDown className="h-3.5 w-3.5" />
                                </Button>
                            </TooltipTrigger>
                            <TooltipContent>Download as .md</TooltipContent>
                        </TooltipProvider>
                    </Tooltip>
                    <Button variant="ghost" size="icon" className="h-7 w-7" onClick={refresh} disabled={loading}>
                        <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-7 w-7 text-destructive hover:text-destructive" onClick={clear}>
                        <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                </div>
            </CardHeader>
            <CardContent className="space-y-4">
                {/* KPI grid */}
                <div className="grid grid-cols-2 gap-2">
                    <StatCard label="Total Cycles" value={stats?.totalCycles ?? 0} icon={Activity} color="bg-primary" />
                    <StatCard label="Success" value={stats?.successCount ?? 0} icon={CheckCircle2} color="bg-emerald-600" />
                    <StatCard label="Errors" value={stats?.errorCount ?? 0} icon={XCircle} color="bg-destructive" />
                    <StatCard label="Skipped" value={stats?.skippedCount ?? 0} icon={SkipForward} color="bg-muted-foreground" />
                </div>

                {/* Rate + Duration */}
                <div className="grid grid-cols-2 gap-2">
                    <div className="rounded-lg border border-border bg-card p-3">
                        <p className="text-xs text-muted-foreground">Success Rate</p>
                        <p className="text-xl font-bold">
                            {stats?.successRate ?? 0}
                            <span className="text-xs text-muted-foreground ml-0.5">%</span>
                        </p>
                    </div>
                    <div className="rounded-lg border border-border bg-card p-3 flex items-center gap-2">
                        <Clock className="h-4 w-4 text-muted-foreground" />
                        <div>
                            <p className="text-xs text-muted-foreground">Avg Duration</p>
                            <p className="text-sm font-semibold">{stats?.avgDurationMs ?? 0}ms</p>
                        </div>
                    </div>
                </div>

                {/* Last error */}
                {stats?.lastErrorMessage && (
                    <div className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/5 p-3">
                        <AlertTriangle className="h-4 w-4 text-destructive mt-0.5 shrink-0" />
                        <div>
                            <p className="text-xs font-medium text-destructive">Last Error</p>
                            <p className="text-xs text-muted-foreground mt-0.5">{stats.lastErrorMessage}</p>
                        </div>
                    </div>
                )}

                {/* Mini bar chart */}
                <div>
                    <p className="text-xs text-muted-foreground mb-2">Recent Cycles (last 20)</p>
                    <MiniBarChart cycles={stats?.recentCycles ?? []} />
                </div>
            </CardContent>
        </Card>
    );
}
