/**
 * Castle.io request-token helper.
 *
 * Lovable's `/projects/:id/move-to-workspace` (and a growing list of other
 * mutation endpoints) are guarded by Castle's risk engine. A valid PUT now
 * MUST include a fresh `x-castle-request-token` header generated by the
 * Castle JS SDK that lovable.dev loads. Without it the server replies
 * `403 { type: "castle_denied" }`.
 *
 * The Castle SDK exposes `window._castle('createRequestToken')` which
 * returns a `Promise<string>` containing a one-shot token. We resolve it
 * on every request (tokens are not reusable — Castle expects a fresh one
 * per call). Cookies (`__cuid`, `cid`) are sent automatically via
 * `withCredentials: true` on the axios client.
 *
 * Runs in MAIN world on lovable.dev so `window._castle` is directly
 * reachable (see mem://architecture/injection-context-awareness).
 *
 * Failure path: if the SDK is missing or throws, we return `''` and let
 * the caller decide. ws-move detects the resulting `castle_denied` 403
 * and surfaces a toast — no retry, per
 * mem://constraints/no-retry-policy.
 */

import { logError } from './error-utils';
import { log } from './logger';

interface CastleGlobal {
    _castle?: (
        action: 'createRequestToken',
    ) => Promise<string> | string | undefined;
}

const CASTLE_TIMEOUT_MS = 2_000;

/**
 * Resolve a single-use Castle request token for the current page.
 * Returns `''` when the SDK is not loaded or the call fails — never
 * throws.
 */
export async function getCastleRequestToken(): Promise<string> {
    const w = window as unknown as CastleGlobal;
    const castle = typeof w._castle === 'function' ? w._castle : null;
    if (!castle) {
        log('Castle: window._castle missing — request will go without x-castle-request-token', 'warn');
        return '';
    }
    try {
        const tokenPromise: Promise<string | null> = Promise.resolve(
            castle('createRequestToken') as Promise<string> | string | undefined,
        ).then(function (v) { return typeof v === 'string' ? v : ''; });
        const timeoutPromise: Promise<string | null> = new Promise(function (resolve) {
            setTimeout(function () { resolve(null); }, CASTLE_TIMEOUT_MS);
        });
        const raced = await Promise.race<Promise<string | null>>([tokenPromise, timeoutPromise]);
        if (raced == null) {
            log('Castle: createRequestToken timed out after ' + CASTLE_TIMEOUT_MS + 'ms', 'warn');
            return '';
        }
        const token = String(raced);
        log('Castle: request token resolved (len=' + token.length + ')', 'info');
        return token;
    } catch (err: unknown) {
        logError('Castle.createRequestToken', 'SDK threw while creating request token', err);
        return '';
    }
}
